qs.I18N.addResource("en", {
	"qs.ui.calendar.title"       : "{1} / {0}",
	"qs.ui.calendar.weekdays_sn" : "['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']",
	"qs.ui.calendar.weekdays"    : "['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']",
	"qs.ui.calendar.prev_year"   : "Previous year",
	"qs.ui.calendar.next_year"   : "Next year",
	"qs.ui.calendar.prev_month"  : "Previous month",
	"qs.ui.calendar.next_month"  : "Next month",
	"qs.ui.calendar.ap"  		 : "['A', 'P']",
	"qs.ui.datagrid.001"         : "Data is too large that the operation cannot be performed . Whether to clear all selections?",
	"qs.ui.messagebox.info"      : "Information",
	"qs.ui.messagebox.error"     : "Error",
	"qs.ui.messagebox.yes"       : "Yes",
	"qs.ui.messagebox.no"        : "No",
	"qs.ui.messagebox.ok"        : "OK",
	"qs.ui.treeview.loading"     : "Loading...",
	"qs.ui.validate.required"    : "This field is required.",
	"qs.ui.window.close"         : "Close",
	"qs.ui.window.maximize"      : "Maximize",
	
	"amf.disconnected"           : "Network has been disconnected. Please refresh and retry.",
	"wos.desktop.001"			 : "You have not a valid license, please contact your ISP.",
	"wos.desktop.002"			 : "Can't find workflow instance \"{0}\", or task \"{1}\" is not found.",
	"wos.desktop.003"			 : "Workflow error",
	"wos.dictionaryloader.001"	 : "Data dictionary load error:{0}",
	"wos.fileloader.loading"     : "File is loading, please wait...",
	"wos.remoting.loading"       : "Waiting service response...",
	"wos.expression.function.001": "{0} function does not match the number of arguments.",
	"wos.expression.function.002": "{0} function requires at least one parameter.",
	"wos.expression.parser.001"  : "Unrecognized grammatical structure, expression = {0}",
	"wos.expression.parser.002"  : "Invalid number:{0}, expression = {1}",
	"wos.expression.parser.003"  : "Divisor can not be 0, expression = {0}",
	"wos.expression.parser.004"  : "Invalid mathematical operators, expression = {0}",
	"wos.expression.parser.005"  : "Invalid logical operators, expression = {0}",
	"wos.expression.parser.006"  : "Unable to get the variable value:{0}, expression = {1}",
	"wos.expression.parser.007"  : "Object does not support {0} function, expression = {1}",
	"wos.expression.parser.008"  : "Syntax error, expression = {0}",
	"wos.expression.parser.009"  : "Unsupported function:{0}(), expression = {1}",
	"wos.expression.parser.010"  : "Syntax error {0}, expression = {1}",
	"wos.expression.parser.011"  : "Parenthesis mismatch, expression = {0}",
	"wos.expression.parser.012"  : "Invalid numeric constants : {0}, expression = {1}",
	"qs.app.appwindow.001"       : "You currently do not have the appropriate permissions to perform, please contact your system administrator.",
	"qs.app.appwindow.002"       : "Could not find the appropriate menu :{0}",
	"qs.app.appwindow.003"       : "The workflow instance is not specified.",
	"qs.app.appwindow.004"       : "Parameter error, unable to open the workflow window.",
	"qs.app.appwindow.005"       : "Unable to obtain login information, please log in again.",
	"qs.app.appwindow.006"       : "Unable to find a workflow instance.",
	"qs.app.appwindow.007"       : "The current task has been submitted to {0}. Tasks assigned to you may have been forwarded or has been cancelled.",
	"qs.app.appwindow.008"       : "The current task has been submitted to {0}.",
	"qs.app.appwindow.009"       : "Please specify the task that you want to take over or forwarded.",
	"qs.app.appwindow.010"       : "Unable to get work item corresponding to the work form.",
	"qs.app.appwindow.011"       : "Please specify the relevant task form.",
	"qs.app.appwindow.012"       : "Task form is not in the workflow instance.",
	"qs.app.appwindow.013"       : "Unable to find the work item.",
	"qs.app.appwindow.014"       : "This work item has finished, it cannot be done again.",
	"qs.app.appwindow.015"       : "Unable to find the workflow objects.",
	"qs.app.appwindow.016"       : "Work form url error, cannot open.",
	"qs.app.appwindow.017"       : "You have no work items to handle.",
	
	"_empty":""
});
